print('+------------------------------------------------------------------------------------------------+')
print('|                                                                                                |')
print('| print                                                           October 2025                   |')
print('|                                                                                                |')
print('|      Dear Sir/Madam,                                                                           |')
print('|                                                                                                |')
print('|       I am writing to express my motivation to apply for this opportunity.                     |')
print('|                                                                                                |')
print('|       I am eager to learn, contribute, and develop my skills in a professional environment     |')
print('|                                                                                                |')
print('|       I am hardworking, responsible, and able to work well both -                              |')
print('|       independently and as part of a team.                                                     |')
print('|                                                                                                |')
print('|        I believe my positive attitude and willingness to take on -                             |')
print('|       new challenges would allow me to make a valuable contribution.                           |')
print('|                                                                                                |')
print('|       Thank you for considering my application.                                                |')
print('|                                                                                                |')
print('|      I would welcome the opportunity to discuss my interest and qualifications further.        |')
print('|                                                                                                |')
print('|       Sincerely,                                                                               |')
print('|       Prashant Yadav                                                                           |')
print('|                                                                                                |')
print('+------------------------------------------------------------------------------------------------+')