print('+------------------------------------------------------------------------------------------------+')
print("|                                                                                                |")
print("|        Hey Baby ❤️,                                                                             |")
print("|                                                                                                |")
print("|        You make my days better just by being in my life.                                       |")
print("|                                                                                                |")
print("|                                                                                                |")
print("|        I love your smile, your cute little attitude, and everything about you. 😘              |")
print("|                                                                                                |")
print("|        Honestly, I dont need anything fancy… just you, your hugs, and maybe a few kisses. 😉❤️  |")
print("|                                                                                                |")
print("|        I am really lucky to have you. Love you! ❤️                                              |")
print("|                                                                                                |")
print('+------------------------------------------------------------------------------------------------+')